name: frontend
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State
  flutter_riverpod: ^3.2.1
  riverpod_annotation: ^4.0.2
  
  # Network & Auth
  connectivity_plus: ^7.1.1
  cookie_jar: ^4.0.9
  dio: ^5.9.2
  dio_cookie_manager: ^3.4.0
  retrofit: ^4.9.2

  # Storage
  flutter_secure_storage: ^10.0.0
  shared_preferences: ^2.5.5
  drift: ^2.31.0
  sqlite3_flutter_libs: 0.5.42

  # Crypto
  bip39: ^1.0.6
  cryptography: ^2.9.0

  # Models
  freezed_annotation: ^3.1.0
  json_annotation: ^4.11.0

  # UI
  flutter_quill: ^11.5.0
  flutter_quill_extensions: ^11.0.0
  slang_flutter: ^4.14.0
  cupertino_icons: ^1.0.9
  google_fonts: ^8.0.2
  flex_color_scheme: ^8.4.0
  table_calendar: ^3.2.0
  pattern_lock: ^2.0.0

  # Navigation
  go_router: ^17.2.2

  # Testing
  mocktail: ^1.0.5

  # Utils
  path: ^1.9.1
  path_provider: ^2.1.5
  uuid: ^4.5.3
  unorm_dart: ^0.3.2
  fpdart: ^1.2.0
  logger: ^2.7.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  # Builders
  build_runner: ^2.14.1
  riverpod_generator: ^4.0.3
  retrofit_generator: ^10.2.5
  drift_dev: ^2.31.0
  freezed: ^3.2.5
  json_serializable: ^6.13.0
  go_router_builder: ^4.3.0

  # Linting
  very_good_analysis: ^10.2.0

flutter:
  assets:
    - assets/images/

  uses-material-design: true
